"""
Generative AI models - perplexity ai

__author__ = "vci"
__copyright__ = "Copyright 2025, vci"
__license__ = "MIT"
__version__ = "1.0.0.10"
__maintainer__ = "vci"
__email__ = "modernui.app@gmail.com"
__status__ = "development"
__reference__ = "vci"

"""

import requests
import json
from PIL import Image
from io import BytesIO
from perplexity import Perplexity

class GenerativeAI:
    def __init__(self, api_key: str) -> None:
        self.genai_client = Perplexity(api_key=api_key)

    def generate_text(self, prompt: str, model: str = "") -> str:
        """
        generate content by perplexity ai
        
        :param prompt: user prompt
        :type prompt: str
        :param model: model used
        :type model: str
        :return: content generated by model
        :rtype: str
        """

        response = self.genai_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "user", "content": prompt}
            ],
            max_tokens=4096,
            temperature=0.7
        )

        print(f"response: {response}")
        return response.choices[0].message.content